/cm/shared/apps/python/3.5.2/lib/python3.5/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
parameters: {'freeze_pre_trained_layers': False, 'test_batch_size': 128, 'model_load_path': 'models/VDCNN/ag_news-2000_model.pt', 'maxlen': 1024, 'batch_size': 128, 'last_pooling_layer': 'k-max-pooling', 'num_embedding_features': 100, 'shuffle': True, 'model_save_path': 'models/VDCNN/VDCNN_ng20---ag_news_depth@9/100', 'test_dataset': 'ng20', 'depth': 9, 'class_weights': None, 'joint_training': True, 'num_prev_classes': 20, 'test_interval': 1000, 'validation_ratio': 0.1, 'seed': 1337, 'chunk_size': 2048, 'dataset': 'ag_news', 'lr_halve_interval': 15000.0, 'lr': 0.01, 'shortcut': False, 'joint_ratio': 1.0, 'test_only': 0, 'joint_test': 0, 'iterations': 50000, 'transfer_lr': 0.001, 'model_folder': 'models/VDCNN/VDCNN_ng20---ag_news_depth@9/100', 'transfer_weights': False, 'combined_datasets': 'ng20---ag_news', 'gpu': True}
Joint Training !
dataset: Newsgroup20, n_classes: 20
  - loading dataset...
dataset: AgNews, n_classes: 4
  - loading dataset...
Both datasets loaded, going to mix ...
Transfer Data Size: 120000
Transfer Ratio Size: 120000
Root dataset Test length - sentences 5645, labels 5645
Transfer dataset Test length - sentences 7600, labels 7600
Unused dataset Test length - sentences 0, labels 0
Mixed dataset Test length - sentences 13245, labels 13245
Mixed dataset Train length - sentences 133179, labels 133179
 Joint Training: Txt vectorization...
--- Logging error ---
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/main.py", line 87, in <module>
    joint_train(opt, logger)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 282, in joint_train
    logger.info("n_txt_feats before overriding: ", n_txt_feats)
Message: 'n_txt_feats before overriding: '
Arguments: (87,)
--- Logging error ---
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/main.py", line 87, in <module>
    joint_train(opt, logger)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 282, in joint_train
    logger.info("n_txt_feats before overriding: ", n_txt_feats)
Message: 'n_txt_feats before overriding: '
Arguments: (87,)
--- Logging error ---
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/main.py", line 87, in <module>
    joint_train(opt, logger)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 284, in joint_train
    logger.info("Number of classes in the mixed dataset are: ", n_classes, type(n_classes))
Message: 'Number of classes in the mixed dataset are: '
Arguments: (24, <class 'int'>)
--- Logging error ---
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/main.py", line 87, in <module>
    joint_train(opt, logger)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 284, in joint_train
    logger.info("Number of classes in the mixed dataset are: ", n_classes, type(n_classes))
Message: 'Number of classes in the mixed dataset are: '
Arguments: (24, <class 'int'>)
--- Logging error ---
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/main.py", line 87, in <module>
    joint_train(opt, logger)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 287, in joint_train
    logger.info("Seed for random numbers: ", torch.initial_seed())
Message: 'Seed for random numbers: '
Arguments: (1337,)
--- Logging error ---
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/main.py", line 87, in <module>
    joint_train(opt, logger)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 287, in joint_train
    logger.info("Seed for random numbers: ", torch.initial_seed())
Message: 'Seed for random numbers: '
Arguments: (1337,)
--- Logging error ---
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/main.py", line 87, in <module>
    joint_train(opt, logger)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 290, in joint_train
    logger.info("Overriding the number of embedding features to: ", n_txt_feats)
Message: 'Overriding the number of embedding features to: '
Arguments: (100,)
--- Logging error ---
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/main.py", line 87, in <module>
    joint_train(opt, logger)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 290, in joint_train
    logger.info("Overriding the number of embedding features to: ", n_txt_feats)
Message: 'Overriding the number of embedding features to: '
Arguments: (100,)
Joint training
Setting the lr to : 0.01
/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py:148: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  yhat = nn.functional.softmax(yhat)
Mixed_ng20---ag_news_1.0 - Iter [0/50000]: train-metrics- {'accuracy': 0.0, 'logloss': -1} ; val-metrics- {'accuracy': 0.004580267307403514, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [1000/50000]: train-metrics- {'accuracy': 0.6796875, 'logloss': -1} ; val-metrics- {'accuracy': 0.005856735245532362, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [2000/50000]: train-metrics- {'accuracy': 0.75, 'logloss': -1} ; val-metrics- {'accuracy': 0.006532512389247635, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [3000/50000]: train-metrics- {'accuracy': 0.890625, 'logloss': -1} ; val-metrics- {'accuracy': 0.006757771437152726, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [4000/50000]: train-metrics- {'accuracy': 0.8828125, 'logloss': -1} ; val-metrics- {'accuracy': 0.006607598738549332, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [5000/50000]: train-metrics- {'accuracy': 0.8671875, 'logloss': -1} ; val-metrics- {'accuracy': 0.005030785403213695, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [6000/50000]: train-metrics- {'accuracy': 0.8671875, 'logloss': -1} ; val-metrics- {'accuracy': 0.005706562546928968, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [7000/50000]: train-metrics- {'accuracy': 0.8828125, 'logloss': -1} ; val-metrics- {'accuracy': 0.005931821594834059, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [8000/50000]: train-metrics- {'accuracy': 0.9296875, 'logloss': -1} ; val-metrics- {'accuracy': 0.007283375882264604, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [9000/50000]: train-metrics- {'accuracy': 0.953125, 'logloss': -1} ; val-metrics- {'accuracy': 0.005556389848325575, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [10000/50000]: train-metrics- {'accuracy': 0.9453125, 'logloss': -1} ; val-metrics- {'accuracy': 0.00863493016969515, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [11000/50000]: train-metrics- {'accuracy': 0.9453125, 'logloss': -1} ; val-metrics- {'accuracy': 0.006307253341342544, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [12000/50000]: train-metrics- {'accuracy': 0.953125, 'logloss': -1} ; val-metrics- {'accuracy': 0.008785102868298544, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [13000/50000]: train-metrics- {'accuracy': 0.9609375, 'logloss': -1} ; val-metrics- {'accuracy': 0.005481303499023878, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [14000/50000]: train-metrics- {'accuracy': 0.9609375, 'logloss': -1} ; val-metrics- {'accuracy': 0.008785102868298544, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [15000/50000]: train-metrics- {'accuracy': 0.9140625, 'logloss': -1} ; val-metrics- {'accuracy': 0.005556389848325575, 'logloss': -1}
new lr: 0.005
Mixed_ng20---ag_news_1.0 - Iter [16000/50000]: train-metrics- {'accuracy': 0.9453125, 'logloss': -1} ; val-metrics- {'accuracy': 0.007884066676678179, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [17000/50000]: train-metrics- {'accuracy': 0.953125, 'logloss': -1} ; val-metrics- {'accuracy': 0.006682685087851028, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [18000/50000]: train-metrics- {'accuracy': 0.9765625, 'logloss': -1} ; val-metrics- {'accuracy': 0.007508634930169695, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [19000/50000]: train-metrics- {'accuracy': 0.9375, 'logloss': -1} ; val-metrics- {'accuracy': 0.007133203183661211, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [20000/50000]: train-metrics- {'accuracy': 0.953125, 'logloss': -1} ; val-metrics- {'accuracy': 0.007133203183661211, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [21000/50000]: train-metrics- {'accuracy': 0.953125, 'logloss': -1} ; val-metrics- {'accuracy': 0.006832857786454423, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [22000/50000]: train-metrics- {'accuracy': 0.953125, 'logloss': -1} ; val-metrics- {'accuracy': 0.0074335485808679986, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [23000/50000]: train-metrics- {'accuracy': 0.953125, 'logloss': -1} ; val-metrics- {'accuracy': 0.006457426039945938, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [24000/50000]: train-metrics- {'accuracy': 1.0, 'logloss': -1} ; val-metrics- {'accuracy': 0.0063823396906442405, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [25000/50000]: train-metrics- {'accuracy': 0.96875, 'logloss': -1} ; val-metrics- {'accuracy': 0.007959153025979876, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [26000/50000]: train-metrics- {'accuracy': 0.9765625, 'logloss': -1} ; val-metrics- {'accuracy': 0.007358462231566301, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [27000/50000]: train-metrics- {'accuracy': 0.984375, 'logloss': -1} ; val-metrics- {'accuracy': 0.007808980327376483, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [28000/50000]: train-metrics- {'accuracy': 0.984375, 'logloss': -1} ; val-metrics- {'accuracy': 0.006457426039945938, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [29000/50000]: train-metrics- {'accuracy': 0.96875, 'logloss': -1} ; val-metrics- {'accuracy': 0.007808980327376483, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [30000/50000]: train-metrics- {'accuracy': 0.96875, 'logloss': -1} ; val-metrics- {'accuracy': 0.006457426039945938, 'logloss': -1}
new lr: 0.0025
Mixed_ng20---ag_news_1.0 - Iter [31000/50000]: train-metrics- {'accuracy': 0.984375, 'logloss': -1} ; val-metrics- {'accuracy': 0.007808980327376483, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [32000/50000]: train-metrics- {'accuracy': 0.9921875, 'logloss': -1} ; val-metrics- {'accuracy': 0.006532512389247635, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [33000/50000]: train-metrics- {'accuracy': 1.0, 'logloss': -1} ; val-metrics- {'accuracy': 0.006983030485057816, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [34000/50000]: train-metrics- {'accuracy': 0.984375, 'logloss': -1} ; val-metrics- {'accuracy': 0.006983030485057816, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [35000/50000]: train-metrics- {'accuracy': 1.0, 'logloss': -1} ; val-metrics- {'accuracy': 0.007133203183661211, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [36000/50000]: train-metrics- {'accuracy': 0.9921875, 'logloss': -1} ; val-metrics- {'accuracy': 0.007208289532962907, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [37000/50000]: train-metrics- {'accuracy': 1.0, 'logloss': -1} ; val-metrics- {'accuracy': 0.006983030485057816, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [38000/50000]: train-metrics- {'accuracy': 1.0, 'logloss': -1} ; val-metrics- {'accuracy': 0.007133203183661211, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [39000/50000]: train-metrics- {'accuracy': 1.0, 'logloss': -1} ; val-metrics- {'accuracy': 0.007133203183661211, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [40000/50000]: train-metrics- {'accuracy': 0.9921875, 'logloss': -1} ; val-metrics- {'accuracy': 0.007208289532962907, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [41000/50000]: train-metrics- {'accuracy': 1.0, 'logloss': -1} ; val-metrics- {'accuracy': 0.0070581168343595135, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [42000/50000]: train-metrics- {'accuracy': 1.0, 'logloss': -1} ; val-metrics- {'accuracy': 0.007133203183661211, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [43000/50000]: train-metrics- {'accuracy': 1.0, 'logloss': -1} ; val-metrics- {'accuracy': 0.007133203183661211, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [44000/50000]: train-metrics- {'accuracy': 1.0, 'logloss': -1} ; val-metrics- {'accuracy': 0.007508634930169695, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [45000/50000]: train-metrics- {'accuracy': 1.0, 'logloss': -1} ; val-metrics- {'accuracy': 0.007208289532962907, 'logloss': -1}
new lr: 0.00125
Mixed_ng20---ag_news_1.0 - Iter [46000/50000]: train-metrics- {'accuracy': 1.0, 'logloss': -1} ; val-metrics- {'accuracy': 0.007283375882264604, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [47000/50000]: train-metrics- {'accuracy': 1.0, 'logloss': -1} ; val-metrics- {'accuracy': 0.0074335485808679986, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [48000/50000]: train-metrics- {'accuracy': 1.0, 'logloss': -1} ; val-metrics- {'accuracy': 0.0074335485808679986, 'logloss': -1}
Mixed_ng20---ag_news_1.0 - Iter [49000/50000]: train-metrics- {'accuracy': 1.0, 'logloss': -1} ; val-metrics- {'accuracy': 0.0074335485808679986, 'logloss': -1}
After Training: Testing on root dataset only
Traceback (most recent call last):
  File "/home/usaxena/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 482, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: invalid argument 2: sizes do not match at /pytorch/torch/lib/THC/generic/THCTensorCopy.c:51

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/cm/shared/apps/python/3.5.2/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/main.py", line 87, in <module>
    joint_train(opt, logger)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 314, in joint_train
    test(model, logger, opt, root_te_data, n_classes, dataset_name)
  File "/home/usaxena/work/s18/lex/code/vdcnn/src/VDCNN.py", line 261, in test
    model.load_state_dict(checkpoint['model'])
  File "/home/usaxena/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 487, in load_state_dict
    .format(name, own_state[name].size(), param.size()))
RuntimeError: While copying the parameter named embed.weight, whose dimensions in the model are torch.Size([100, 16]) and whose dimensions in the checkpoint are torch.Size([66, 16]).
